
name: 'netflix_dbt_project'
version: '1.0.0'


profile: 'netflix_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  netflix_dbt_project:
    +materialized: view
    dim:
      +materialized: table
    fct:
      +materialized: table